### ISSUE TITLE
Don't fail if there is no package.json

### ISSUE THREAD

**Issue by michaelcontento** [gnandretta/babel-plugin-version-inline#2]
Instead of failing this plugin could simply expose `undefined` as `__VERSION__`. 

What do you think about this?

**Comment by gnandretta** [comment]
I don't know, seems kinda dangerous. Do you have any use cases?

**Comment by michaelcontento** [comment]
Mostly it would allow one to use this plugin in a preset no matter if there is a `package.json` or not. But yes, it might be dangerous. 

Feel free to close this issue, if you don't like this feature/idea 😄

**Comment by miracle2k** [comment]
FWIW, I am getting an error related to this and babel-preset-michaelcontento, by way of using redux-storage-merger-immutablejs and testing with ava. It says it cannot open package.json. I am not sure where it is looking for package.json exactly, but I fixed it for now by deleting the .babelrc in redux-storage-merger-immutablejs.

**Comment by michaelcontento** [comment]
@miracle2k Note that [babel-preset-michaelcontento](https://github.com/michaelcontento/babel-preset-michaelcontento) has been deprecated in favor of [babel-preset-modern-node](https://github.com/michaelcontento/babel-preset-modern-node) and that I updated all `redux-storage*` packages yesterday 😄

**Comment by michaelcontento** [comment]
@gnandretta I'll go ahead and close this issue, as it's fine to fail hard if the current version can't be detected. Maybe a soft failure would be okay but no failure at all (as I suggested with `undefined`) might only lead to confusion / errors / bugs.
